# binder environment
name: jupysql-binder

channels:
  - conda-forge

dependencies:
  - python=3.10
  - matplotlib
  - pandas
  - pip
  # by default binder runs an old version of jupyterlab
  # that doesn't work with jupysql-plugin
  - jupyterlab<4
  - pip:
    - jupyter-book
    # duckdb example
    - duckdb
    - duckdb-engine
    # plot example
    - memory-profiler
    - pyarrow
    # package
    - -e .
    # to add sql syntax highlighting + formatting
    - jupysql-plugin
    # required to open .md files as nbs
    - jupytext
