[tool.pytest.ini_options]
addopts = "--pdbcls=IPython.terminal.debugger:Pdb"

[tool.pkgmt]
github = "ploomber/jupysql"


[tool.pkgmt.check_links]
extensions = ["md", "rst", "py", "ipynb"]
ignore_substrings = ["d37ci6vzurychx.cloudfront.net"]

[tool.nbqa.addopts]
flake8 = [
    # notebooks allow non-top imports
    "--extend-ignore=E402",
    # jupysql notebooks might have "undefined name" errors
    # due to the << operator
    "--ignore=F821",
]
