name: jupysql-doc

channels:
  - conda-forge


dependencies:
  - python=3.10
  - matplotlib
  - pandas
  - pip
  - pip:
    - -e ..
    - jupyter-book
    # duckdb example
    - duckdb>=0.7.1
    - duckdb-engine
    # plot example
    - memory-profiler
    - pyarrow
    - pkgmt>=0.1.7
    # convert to polars example
    - polars
    # for developer guide
    - pytest
    # for %%sql --interact
    - ipywidgets