name: jupysql-doc

channels:
  - conda-forge


dependencies:
  - python=3.10
  - matplotlib
  - pandas
  - pip
  - pip:
    - jupyter-book<0.14
    # duckdb example
    - duckdb
    - duckdb-engine
    # plot example
    - memory-profiler
    - pyarrow
    - pkgmt>=0.1.7
    # convert to polars example
    - polars
    # for developer guide
    - pytest
    - -e ..